In [12]:
print("hello")

hello


In [13]:
a = 1

In [14]:
a

1

In [15]:
b = [1, 2, 3, 4, 5]

In [17]:
b

[1, 2, 3, 4, 5]

In [24]:
import numpy as np #as : 이제부터 numpy를 할건데 np라고 하겠다.
x = np.array([3,1,2])
print(x)
print(type(x))
print(type([3,1,2]))
'''
numpy는 하나의 타입만 지원한다.
-> x = np.array([3,1,2,'1']) 입력시 모두 스트링으로 출력됨
'''

[3 1 2]
<class 'numpy.ndarray'>
<class 'list'>


"\nnumpy는 하나의 타입만 지원한다.\n-> x = np.array([3,1,2,'1']) 입력시 모두 스트링으로 출력됨\n"

In [29]:
c = [[1], [1,2]]
d = np.array([[1,1], [1,2]])

for x,y in d:
    print(x,y)

1 1
1 2


In [31]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [36]:
h = np.array([3, 6])
print(h)
print(h.shape)

[3 6]
(2,)


In [35]:
# x = np.array([1.0, 2.0, 3.0])
# y = np.array([2.0, 4.0, 6.0])
print(x.shape) #.shap:  배열 각 차원의 크기를 튜플 형태로 표현 -> 1차원 + 1차원= 2차원, 1차 + 1차 +1차 =3차원

print(x.dtype)
print(x / 2.0)

(3,)
float64
[0.5 1.  1.5]


In [41]:
a = np.array([[1,2],[3,4],[5,6]])

print(a.ndim)
print(a.shape)

2
(3, 2)


In [42]:
a = np.array([[[1],[2]],[[3],[4]],[[5],[6]]])

print(a.ndim)
print(a.shape) #

3
(3, 2, 1)


In [43]:
a = np.array([[[1,2],[2,2]],[[3,2],[4,2]],[[5,2],[6,2]]])

print(a.ndim)
print(a.shape) #큰상자 3개 안에, 작은상자 2개 있고, 그 안에 원소 2개가 있으니까 (3,2,2)

3
(3, 2, 2)
