In [2]:
#차원 확장
#expanded
import numpy as np

a = np.array([[1,2], [3,4]])

In [4]:
expanded = np.expand_dims(a, 0)
print(expanded)
print(expanded.shape)

[[[1 2]
  [3 4]]]
(1, 2, 2)


In [6]:
#차원 축소
#squeeze(arr, axis)
np_ones = np.ones((1,2,1,3))
print(np_ones)

[[[[1. 1. 1.]]

  [[1. 1. 1.]]]]


In [10]:
sqeezed = np.squeeze(np_ones)
print(sqeezed) 
print(sqeezed.shape) 

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [13]:
#unique
a= [1,1,2,2,3,3,3,4,4]
u_a, counts = np.unique(a, return_counts = True)
print(u_a) 
print(counts) 

[1 2 3 4]
[2 2 3 2]


In [15]:
a = [ 1,2,2,3,4,3,4,3,1]
u_a, indexs = np.unique(a,return_index = True)
print(u_a) 
print(indexs) 

[1 2 3 4]
[0 1 3 4]


In [19]:
a = [ 1,2,2,3,4,3,4,3,1]
u_a, indexs,counts = np.unique(a,return_index = True, return_counts = True)
print(u_a) #중복되는 숫자가 뭐가 있어?
print(indexs) #중복이 시작되는 인덱스 자리 번호
print(counts) #중복 개수

[1 2 3 4]
[0 1 3 4]
[2 2 3 2]


In [39]:
#실습.
def add(a=1, b=1): #a=1, b=1은 기본값 -> 값이 따로 정해지지 않을때 1로 쓴다.
    return a,b,a+b

a,b,sum = add(b=2, a=3)
print(a,b,sum)

3 2 5


In [28]:
#정렬
#np.argsort(array): 행렬이 정렬되고 난 후 해당 원소의 인덱스 자리 반환
a = np.array([1,4,2,3])
b = np.sort(a) # a[np.argsort(a)]
print(f"a {a}")
print(f"b {b}")
c = np.argsort(a)
print(f"c {c}")
print(f"cc {a[c]}")
a.sort()
print(f"a {a}")
print()

a[c.sort()]

a [1 4 2 3]
b [1 2 3 4]
c [0 2 3 1]
cc [1 2 3 4]
a [1 2 3 4]



array([[1, 2, 3, 4]])

In [30]:
#그 밖에 유용한 함수
a = np.array([1,4,2,3])
np.mean(a) #평균값

2.5

In [31]:
np.std(a) #표준편차

1.118033988749895

In [32]:
np.var(a) #분산

1.25

In [33]:
np.max(a)

4

In [34]:
np.min(a)

1

In [35]:
np.sum(a)

10

In [36]:
np.prod(a) #곱

24

In [37]:
np.median(a) #중앙값

2.5

In [40]:
# axis=0 행, axis=1 열

In [48]:
#실습. Numpy 모듈 사용해보기3
#1. 중복을 제거한 배열 출력
a = [1,1,2,3,4,5,5,5,5,7,8,9,10,11,24,100]
unique_a = np.unique(a)
print(unique_a)

[  1   2   3   4   5   7   8   9  10  11  24 100]


In [59]:
#2. 1의 결과의 최대, 최소, 평균값 출력
print(np.max(unique_a))
print(np.min(unique_a))
print(np.mean(unique_a))


100
1
8.333333333333334


In [53]:
#3. 1의 결과의 모든 합 출력
max_a = np.max(unique_a)
min_a = np.min(unique_a)
mean_a = np.mean(unique_a)

np.sum(max_a + min_a + mean_a)

109.33333333333333

In [55]:
#4. 중복을 제거하지 않은 배열의 중간값 출력
np.median(a)

5.0

In [83]:
#실습. Numpy 모듈 사용해보기3
x = np.arange(15, dtype=np.int64).reshape(3, 5)
x[1:, ::2] = -99
print(x)

[[  0   1   2   3   4]
 [-99   6 -99   8 -99]
 [-99  11 -99  13 -99]]


In [84]:
#
x[1,1]
x[-1,-1]
x[:,0]
x[1,:]
x[1,1]
x[:2, :2]
x[-2:,-2:]

array([[  8, -99],
       [ 13, -99]], dtype=int64)

In [73]:
#1. 1열의 최대, 최소 평균값 출력
ndarr = x[0:1]

print(f'최대값: {np.max(ndarr)}')
print(f'최소값: {np.min(ndarr)}')
print(f'평균값: {np.mean(ndarr)}')

최대값: 4
최소값: 0
평균값: 2.0


In [78]:
#2. 2행의 모든 합 출력
ndarr_2 = x[1:2]
print(np.sum(ndarr_2))


-283


In [85]:
#3. 실습 2번 1차원 배열을 argsort 이용하여 내림차순 정렬
arg_x = np.argsort(a)
print(a[arg_x])

arg_x_rev = arg_x[::-1]
print(a[arg_x_rev])


TypeError: only integer scalar arrays can be converted to a scalar index