In [1]:
# Numpy: numerical python의 약자. 수치해석, 통계 관련 계산을 구현할 때 사용하는 모듈
import numpy as np #as : 이제부터 numpy를 할건데 np라고 하겠다.
x = np.array([3,1,2])
print(x)
print(type(x))
print(type([3,1,2]))
'''
numpy는 하나의 타입만 지원한다.
-> x = np.array([3,1,2,'1']) 입력시 모두 스트링으로 출력됨
'''

[3 1 2]
<class 'numpy.ndarray'>
<class 'list'>


"\nnumpy는 하나의 타입만 지원한다.\n-> x = np.array([3,1,2,'1']) 입력시 모두 스트링으로 출력됨\n"

In [2]:
# numpy 배열 형태
c = np.array[[1], [1,2]] # (x)
'''
배열형태가 list와 비슷하지만 차이 알아두어야함
list: 내부 배열의 원소 개수가 달라도 된다.
numpy: 내부 배열의 원소 개수가 같아야 한다. 다르면 오류남
'''
d = np.array([[1,1], [1,2]]) # (o)

for x,y in d:
    print(x,y)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [3]:
#연산이 가능
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [4]:
# numpy관련 메소드(ndim, shape)
h = np.array([3, 6])
print(h)
print(h.shape)

[3 6]
(2,)


In [5]:
# x = np.array([1.0, 2.0, 3.0])
# y = np.array([2.0, 4.0, 6.0])
print(x.shape) #.shap:  배열 각 차원의 크기를 튜플 형태로 표현 

print(x.dtype)
print(x / 2.0)

(3,)
float64
[0.5 1.  1.5]


In [6]:
a = np.array([[1,2],[3,4],[5,6]])

print(a.ndim)
print(a.shape)

2
(3, 2)


In [7]:
a = np.array([[[1],[2]],[[3],[4]],[[5],[6]]])

print(a.ndim)
print(a.shape) 

3
(3, 2, 1)


In [8]:
a = np.array([[[1,2],[2,2]],[[3,2],[4,2]],[[5,2],[6,2]]])

print(a.ndim) # 대괄호 갯수
print(a.shape) #큰상자 3개 안에, 작은상자 2개 있고, 그 안에 원소 2개가 있으니까 (3,2,2)

3
(3, 2, 2)


In [9]:
a = np.array([[[[1],[2]],[[2],[2]]],[[[3],[2]],[[4],[2]]],[[[5],[2]],[[6],[2]]]])

print(a.ndim)
print(a.shape)

4
(3, 2, 2, 1)


In [10]:
#np.dot(array1, array2): 배열의 내적 연산
np.dot(4,2) 
'''
0차원: 스칼라의 곱
1차원: 벡터의 내적 연산
2차원: 행렬곱 연산(but, 행렬곱 연산의 경우 matmul()사용)
'''

8

In [11]:
ndar1 = np.array([3,2]) # ndarray : numpy는 ndarray 타입의 배열을 만들 수 있다.(ndarray: N-dimension array의 약자. 다차원 배열)
ndar2 = np.array([4,6])
np.dot(ndar1, ndar2)

24

In [12]:
ndar1 = np.array([[1,2], [3,4]])
ndar2 = np.array([[1,2], [3,4]])
np.dot(ndar1, ndar2)

#행렬에서 (행*열) -> AXB 연산을 [2*3] x [3*2] 
# -> 안쪽이 3*3으로 같으므로 연산 가능o
# -> 바깥쪽의 곱으로 행렬이 정렬되므로 결과는 2*2행렬

array([[ 7, 10],
       [15, 22]])

In [5]:
#ㄴ에러
ndar1 = np.array([[1], [3]]) # 2*1
ndar2 = np.array([[1,2], [3,4]]) # 2*2 이므로 연산 불가
np.dot(ndar1, ndar2)

ValueError: shapes (2,1) and (2,2) not aligned: 1 (dim 1) != 2 (dim 0)

In [14]:
# np.eye(n): n*n크기의 단위 행렬 생성
# 단위행렬: 곱해서 자기자신이 나오게 하는 것
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
# flatten
ndar2 = np.array([[[1],[2]], [[3],[4]]])
print(ndar2.shape)
print(ndar2.ndim)

a = ndar2.flatten() #.flatten: 평탄화(N차원 배열을 1차원 배열로 변환시켜주는 작업)
print(a.ndim)
print(ndar2)

(2, 2, 1)
3
1
[[[1]
  [2]]

 [[3]
  [4]]]


In [72]:
#.reshape(행, 열): 배열의 차원을 변경
# 기존 행렬의 원소와 만들고자 하는 행열의 원소의 갯수가 같아야 생성됨!
ndarr = np.array([[1,2], [2,3], [3,4]])
ndarr.reshape(2,3) #.reshape(2,3):2행3열 배열의 행열을 만들어라 
print(ndarr)

[[1 2]
 [2 3]
 [3 4]]


In [17]:
ndarr.reshape(6,1)

array([[1],
       [2],
       [2],
       [3],
       [3],
       [4]])

In [18]:
ndarr.flatten()

array([1, 2, 2, 3, 3, 4])

In [29]:
# Numpy관련 메소드 random
np.random.randint(5, size=(2,4)) 
'''
5: 0~4까지의 난수
size=(2,4): 2행 4열열
-> 0~4까지의 난수 중에서 2행 4열열으로 랜덤으로 배열해라
'''

array([[0, 2, 1, 0],
       [0, 1, 2, 4]])

In [71]:
#rand(행, 열): 0이상 1미만의 행렬 값을 생성하도록 설계되어 있음
np.random.rand(2,4)

array([[0.18393692, 0.60720549, 0.82527421, 0.01519785],
       [0.03643473, 0.14606547, 0.95385693, 0.5634402 ]])

In [86]:
# 초기화
rng = np.random.default_rng()

In [84]:
rng.random() # 0과 1사이의 난수

0.7739560485559633

In [82]:
#rng.integers(low, high, size)
rng.integers(0, 10, (2,4)) #0이상 10미만의 2행 4열로 지정된 범위의 정수 난수

array([[6, 0, 4, 6],
       [9, 0, 1, 9]], dtype=int64)

In [24]:
#관련메소드, 조건식 #굉장이 중요함!!!
ndarr = np.array([[6,3], [5,2], [4,1]])
ndarr > 4 #각 요소가 1보다 큰게 있는가?
#결과값은 같은 크기의 Boolean배열로 반환환

array([[ True, False],
       [ True, False],
       [False, False]])

In [25]:
ndarr = np.array([[6,3], [5,2], [4,1]])
ndarr[ndarr > 4] 
#ㄴBoolean배열로 반환된 값에서 True 값들만 반환
#ㄴ1차원 배열로 생성.

array([6, 5])

In [26]:
ndarr = np.array([[6,3], [5,2], [4,1]])
ndarr[ndarr > 1]

array([6, 3, 5, 2, 4])

In [27]:
#슬라이싱
ndarr[1:] #인데스의 1번 인덱스부터 끝까지 반환하라

array([[5, 2],
       [4, 1]])