In [66]:
#실습. Numpy 모듈 사용해보기1
import numpy as np
a1 = np.zeros(10)
print(a1,'\n')

a1[4] = 1
print(a1,'\n')

print(np.arange(10,31),'\n')

rng = np.random.default_rng() #seed에 따라서 값이 정해져서 나온다.
print(rng.integers(0,99,[2,2]),'\n')

print(rng.random((2,4)),'\n')


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] 

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30] 

[[13 86]
 [54 17]] 

[[0.28925072 0.95994618 0.92178367 0.86451314]
 [0.0063988  0.26168847 0.25430583 0.04795217]] 



In [67]:
# 짚고 넘어가기 
rng = np.random.default_rng(seed=()) #seed에 값을 넣으면 random이어도도 값이 고정되어어 나온다.
print(rng.integers(0,99,[2,2]))

[[84 63]
 [50 26]]


In [81]:
#실습. Numpy 모듈 사용해보기2
# 6번
a6 = np.arange(35,75)
a7 = a6.reshape(10,4)
print(a7)

[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]


In [82]:
# 7번
a8 = a7[::-1]
print(a8)

[[71 72 73 74]
 [67 68 69 70]
 [63 64 65 66]
 [59 60 61 62]
 [55 56 57 58]
 [51 52 53 54]
 [47 48 49 50]
 [43 44 45 46]
 [39 40 41 42]
 [35 36 37 38]]


In [83]:
# 8번
a9 = a7[1:-1, 2:]
print(a9)

[[41 42]
 [45 46]
 [49 50]
 [53 54]
 [57 58]
 [61 62]
 [65 66]
 [69 70]]


In [89]:
# 9번
# 6번
#a6 = np.arange(35,75)
#a7 = a6.reshape(10,4)
#print(a7)
a10 = a7[:, -1]
print(a10)


# 9-1번
a10_1 = a7[:,-1:]
print(a10_1)

[38 42 46 50 54 58 62 66 70 74]
[[38]
 [42]
 [46]
 [50]
 [54]
 [58]
 [62]
 [66]
 [70]
 [74]]


In [94]:
# 10번
a11 = a7[::-1, -1:]
print(a11)

[[74]
 [70]
 [66]
 [62]
 [58]
 [54]
 [50]
 [46]
 [42]
 [38]]


In [96]:
# 11번
ndarr = rng.integers(1,51,size = (5,6))
print(ndarr)
print(ndarr[ndarr % 2 == 0])


[[44  7 29 37 43 27]
 [19 16 22 25 36 45]
 [ 4 47 27 18 34 29]
 [13 17 36 30 26 17]
 [39 20 17 45 14 12]]
[44 16 22 36  4 18 34 36 30 26 20 14 12]
